### PR TITLE
Adds some test scaffolding and fixes partiality/FFI issue.

### PR DESCRIPTION
**Pull request by bbarker**

### CODE REVIEW

**Comment by bbarker** [comment]
Fixes #6 - the issue is that the FFI does not seem to know about `Partial`s, at least it knows enough to typecheck, but doesn't generate the correct code. :-( I did hear that exception handling is still an option with FFIs, and pulp may be a good place to look to find some examples.

**Comment by bbarker** [comment]
Another option, which seems a bit unwieldy to me in this case: "If you need it to have a partial constraint, define the version with the partial constraint in PureScript and don’t export the ffi one". 

I would suggest to remove Partials for now so as to keep the API the same, then possibly add exceptions later, which I gather would change the API as exceptions need to take place in `Effect`.

**Comment by bbarker** [comment]
Effect types are added now

**Comment by toastal** [comment]
Sorry I missed your PR. Github often get sent to my spam folder and there's too many notifications. I see you forked it into community which is :ok_hand:

**Pull request merged**
